### ISSUE TITLE
Fragment flashes after removal animation ends.

### ISSUE THREAD

**Issue by Alok-Sharma** [ferdy182/Android-CircularRevealFragment#2]
I can't figure out why the fragment flashes after removal.

YouTube video: https://www.youtube.com/watch?v=9MBx6kLKZM0
Also asked on StackOverflow: http://stackoverflow.com/questions/28746162/fragment-flashes-after-removal-and-animation-ends

Have you observed this behavior too?

**Comment by ferdy182** [comment]
No, I haven't seen that, can you show me your code?

**Comment by Alok-Sharma** [comment]
Actually, I just fixed it by setting the fragment view invisible right before `beginTransaction().remove(theFragment).commit();`

This prevents the fragment from appearing to flash, since it is not invisible.
I'll try to push the code on to my GitHub soon. I'll let you know when I do that.

**Comment by Alok-Sharma** [comment]
Alright, I just pushed some code [here](https://github.com/Alok-Sharma/CircularRevealFragment)
If you see here at [line 140](https://github.com/Alok-Sharma/CircularRevealFragment/blob/master/app/src/main/java/com/fernandofgallego/ciruclarrevealfragment/CircularRevealingFragment.java#L140) you'll see a make invisible function. I'm calling this function from the main activity right before I remove the fragment at [line 54](https://github.com/Alok-Sharma/CircularRevealFragment/blob/master/app/src/main/java/com/fernandofgallego/ciruclarrevealfragment/MainActivity.java#L54)

Thanks  a lot for making this demo though. It was very helpful!

**Comment by ferdy182** [comment]
Cool, I was thinking about something like that but hiding the fragment also requires a fragment transaction, I didn't think about hiding just the layout, I don't know about side effects but it should be fine.

**Comment by ferdy182** [comment]
I tried myself and it crashes randomly, does it always work for you?

**Comment by Alok-Sharma** [comment]
Yea, I haven't really taken care of the bugs right now in the code, so I'm sure there will be crashes. I just wanted to show you the invisibility part. I think there may be some null pointer exceptions. 
However, I don't think its crashing because of the invisibility set, is it?

**Comment by Alok-Sharma** [comment]
Alright, pull the code now and try again. I'm not facing any more crashes. Let me know if you still get a crash.

**Comment by ferdy182** [comment]
I was able to reproduce the original issue on my repo with a button as you did. It is a strange thing, maybe because you were saving a reference to the fragment but I don't know why it happens.

I downloaded your project and it works but it crashes if you rotate the device and close the fragment :)

**Comment by Alok-Sharma** [comment]
Its weird. I dont think its because of the reference though. I tried this:
- Made a generic method that handles the remove fragment portion (take it out of onFragmentTouched and put it in its own method basically)
- Make a button to call this method.
- Make the onFragmentTouched to call this method when the fragment is touched.

Even though the exact same method is being called by the button and by the fragment touch, the fragment touch will not produce the flash, but the button will. I have no idea how this was happening.

**Comment by ferdy182** [comment]
Exactly. I added your changes to the original repo. Thanks!

**Comment by Alok-Sharma** [comment]
Someone posted a much better solution in the [stackoverflow question](http://stackoverflow.com/a/28752450/595947) I had asked earlier. For this, you just need to execute `getFragmentManager().executePendingTransactions()` after calling remove on your fragment. I can verify that the flashing stopped.

**Comment by ferdy182** [comment]
Great! thank you! I fixed it in the source code. I hope it works much better now. Thanks for the contribution! :+1:
